FROM caleb/nginx:1.9

MAINTAINER Caleb Land <caleb@land.fm>

COPY handlers-enabled/*   /etc/nginx/handlers-enabled/
COPY docker-entrypoint.sh /nginx-php-entrypoint.sh

ENTRYPOINT ["/nginx-php-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
