FROM caleb/nginx:1.10

MAINTAINER Caleb Land <caleb@land.fm>

COPY handlers-enabled/*   /etc/nginx/handlers-enabled/
COPY docker-entrypoint.sh /nginx-rails-entrypoint.sh

ENTRYPOINT ["/nginx-rails-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
